#!/bin/bash
set -ex

echo "Running tests..."

export RUNTIME_DEPS_IMAGE=${1:-"ubuntu/dotnet-runtime-deps:test"}

CURRENT_FOLDER="$(dirname $(readlink -f $0))"

for test_folder in "$CURRENT_FOLDER"/*/
do
    pushd $test_folder

    ./runtest

    popd
done
