ARG UBUNTU_RELEASE=22.04
ARG USER=app UID=101 GROUP=app GID=101

FROM golang:1.18 AS chisel
RUN git clone --depth 1 -b main https://github.com/canonical/chisel /opt/chisel
WORKDIR /opt/chisel
RUN go build ./cmd/chisel

FROM ubuntu:$UBUNTU_RELEASE AS builder
SHELL ["/bin/bash", "-oeux", "pipefail", "-c"]
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
COPY --from=chisel /opt/chisel/chisel /usr/bin/

FROM builder AS rootfs-prep
ARG USER UID GROUP GID
RUN mkdir -p /rootfs/etc \
    && echo "$GROUP:x:$GID:" >/rootfs/etc/group \
    && echo "$USER:x:$UID:$GID::/nohome:/noshell" >/rootfs/etc/passwd

FROM scratch AS image-prep
ENV \
    # Configure web servers to bind to port 8080 when present
    ASPNETCORE_URLS=http://+:8080 \
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true
ARG UID GID
USER $UID:$GID

### BOILERPLATE END ###

FROM rootfs-prep AS sliced-runtime
ARG UBUNTU_RELEASE
RUN chisel cut --release "ubuntu-$UBUNTU_RELEASE" --root /rootfs \
    base-files_base \
    ca-certificates_data \
    dotnet-runtime-6.0_libs \
    && ln -sr /rootfs/usr/lib/dotnet/dotnet6-* /rootfs/usr/lib/dotnet/dotnet6 \
    && mkdir -p /rootfs/usr/bin \
    && ln -s /usr/lib/dotnet/dotnet6/dotnet /rootfs/usr/bin/

FROM image-prep
COPY --from=sliced-runtime /rootfs /
ENTRYPOINT ["/usr/bin/dotnet"]
CMD ["--info"]
