ARG UBUNTU_RELEASE=22.04
ARG USER=app UID=101 GROUP=app GID=101

FROM golang:1.18 AS chisel
ARG UBUNTU_RELEASE

RUN git clone --depth 1 -b main https://github.com/canonical/chisel /opt/chisel \
    && git clone --depth 1 -b "ubuntu-$UBUNTU_RELEASE" https://github.com/cjdcordeiro/chisel-releases /opt/chisel-release  
WORKDIR /opt/chisel
RUN go generate internal/deb/version.go \
    && go build ./cmd/chisel

FROM ubuntu:$UBUNTU_RELEASE AS builder
SHELL ["/bin/bash", "-oeux", "pipefail", "-c"]
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
COPY --from=chisel /opt/chisel/chisel /usr/bin/

FROM builder AS rootfs-prep
ARG USER UID GROUP GID
RUN mkdir -p /rootfs/etc \
    && echo "$GROUP:x:$GID:" >/rootfs/etc/group \
    && echo "$USER:x:$UID:$GID::/nohome:/noshell" >/rootfs/etc/passwd

FROM scratch AS image-prep
ENV \
    # Configure web servers to bind to port 8080 when present
    ASPNETCORE_URLS=http://+:8080 \
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true
ARG UID GID
USER $UID:$GID

### BOILERPLATE END ###

FROM rootfs-prep AS sliced-deps
ARG UBUNTU_RELEASE
COPY --from=chisel /opt/chisel-release /opt/chisel-release
RUN chisel cut --release /opt/chisel-release --root /rootfs \
    base-files_base \
    ca-certificates_data \
    libc6_libs \
    libgcc-s1_libs \
    libssl3_libs \
    libstdc++6_libs \
    zlib1g_libs

FROM image-prep
COPY --from=sliced-deps /rootfs /
# Set the invariant mode since ICU package isn't included (see https://github.com/dotnet/announcements/issues/20)
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true