ARG UBUNTU_RELEASE=24.04
ARG USER=app UID=101 GROUP=app GID=101

FROM ubuntu.azurecr.io/ubuntu:$UBUNTU_RELEASE@sha256:d8e1940c842a6dbc179083ec8c142586170a0259812f2f85e10f12c1239eb432 AS builder
ARG USER UID GROUP GID TARGETARCH UBUNTU_RELEASE
SHELL ["/bin/bash", "-oeux", "pipefail", "-c"]
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates git file \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

ADD "https://github.com/canonical/chisel/releases/download/v0.8.0/chisel_v0.8.0_linux_${TARGETARCH}.tar.gz" chisel.tar.gz
RUN tar -xvf chisel.tar.gz -C /usr/bin/
ADD "https://raw.githubusercontent.com/canonical/rocks-toolbox/main/chisel-wrapper" /usr/bin/chisel-wrapper
RUN chmod +x /usr/bin/chisel-wrapper

RUN mkdir -p /rootfs/etc \
    && install -d -m 0755 -o "$UID" -g "$GID" "/rootfs/home/$USER" \
    && echo -e "root:x:0:\n$GROUP:x:$GID:" >/rootfs/etc/group \
    && echo -e "root:x:0:0:root:/root:/noshell\n$USER:x:$UID:$GID::/home/$USER:/noshell" >/rootfs/etc/passwd

RUN chisel-wrapper --generate-dpkg-status /status -- --release "ubuntu-$UBUNTU_RELEASE" --root /rootfs \
    base-files_base \
    base-files_release-info \
    ca-certificates_data \
    libc6_libs \
    libgcc-s1_libs \
    libssl3_libs \
    libstdc++6_libs \
    zlib1g_libs

FROM scratch AS sbom-prep
COPY --from=builder /rootfs /
COPY --from=builder /status /var/lib/dpkg/status

FROM scratch
ENV \
    # Configure web servers to bind to port 8080 when present
    ASPNETCORE_URLS=http://+:8080 \
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true \
    # Set the invariant mode since ICU package isn't included (see https://github.com/dotnet/announcements/issues/20)
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
ARG USER UID GROUP GID

COPY --from=builder /rootfs /

# Workaround for https://github.com/moby/moby/issues/38710
COPY --from=builder --chown="$UID:$GID" "/rootfs/home/$USER" "/home/$USER"
