#!/bin/bash
set -ex

echo "Running test for .NET Hello World app"

(cd src && dotnet publish --no-self-contained -r linux-x64)

RunContainer() {
    docker run --rm -v $PWD/src:/app:ro --user $1 $RUNTIME_IMAGE /app/bin/Debug/net6.0/linux-x64/Hello.dll
}

RunContainer app
RunContainer root
