#!/bin/bash
set -ex

echo "Running test for .NET HTTPS client app "

(cd src && dotnet publish --no-self-contained -r linux-x64)

docker run --rm -v $PWD/src:/app:ro $RUNTIME_IMAGE /app/bin/Debug/net7.0/linux-x64/Hello.dll
