ARG UBUNTU_RELEASE=22.04
ARG USER=app UID=101 GROUP=app GID=101

FROM golang:1.20 AS chisel
RUN git clone --depth 1 -b main https://github.com/canonical/chisel /opt/chisel
WORKDIR /opt/chisel
RUN go generate internal/deb/version.go \
    && go build ./cmd/chisel
ADD "https://raw.githubusercontent.com/canonical/rocks-toolbox/main/chisel-wrapper" chisel-wrapper
RUN chmod +x chisel-wrapper

FROM ubuntu.azurecr.io/ubuntu:$UBUNTU_RELEASE@sha256:da15d4a10e27ece78bcab8e36d55762d086238ea05f033ccab108d99af3db68e AS builder
SHELL ["/bin/bash", "-oeux", "pipefail", "-c"]
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates file \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
COPY --from=chisel /opt/chisel/chisel /usr/bin/
COPY --from=chisel /opt/chisel/chisel-wrapper /usr/bin/

FROM builder AS rootfs-prep
ARG USER UID GROUP GID
RUN mkdir -p /rootfs/etc \
    && install -d -m 0755 -o $UID -g $GID /rootfs/home/$USER \
    && echo -e "root:x:0:\n$GROUP:x:$GID:" >/rootfs/etc/group \
    && echo -e "root:x:0:0:root:/root:/noshell\n$USER:x:$UID:$GID::/home/$USER:/noshell" >/rootfs/etc/passwd

FROM scratch AS image-prep
ENV \
    # Configure web servers to bind to port 8080 when present
    ASPNETCORE_URLS=http://+:8080 \
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true
ARG UID GID
USER $UID:$GID

### BOILERPLATE END ###

FROM rootfs-prep AS sliced-aspnet
ARG UBUNTU_RELEASE
RUN chisel-wrapper --generate-dpkg-status /status -- --release "ubuntu-$UBUNTU_RELEASE" --root /rootfs \
    base-files_base \
    base-files_release-info \
    ca-certificates_data \
    aspnetcore-runtime-6.0_libs \
    && mkdir -p /rootfs/usr/bin \
    && ln -s /usr/lib/dotnet/dotnet /rootfs/usr/bin/

FROM scratch AS sbom-prep
COPY --from=sliced-aspnet /rootfs /
COPY --from=sliced-aspnet /status /var/lib/dpkg/status

FROM image-prep
ARG USER UID GROUP GID

COPY --from=sliced-aspnet /rootfs /

# Workaround for https://github.com/moby/moby/issues/38710
COPY --from=sliced-aspnet --chown=$UID:$GID /rootfs/home/$USER /home/$USER

ENTRYPOINT ["/usr/bin/dotnet"]
CMD ["--info"]
