ARG UBUNTU_RELEASE=23.04
ARG USER=app UID=101 GROUP=app GID=101

FROM ubuntu.azurecr.io/ubuntu:$UBUNTU_RELEASE@sha256:87482f7d889632e196d4d843867f50d713ed2dfadf6476573f3531854ebf629e AS builder
ARG USER UID GROUP GID TARGETARCH UBUNTU_RELEASE
SHELL ["/bin/bash", "-oeux", "pipefail", "-c"]
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates git file \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
### TODO: REMOVE "git" and this, once .net7 slices are merged upstream
RUN git clone -b "ROCKS-358_dotnet7-lunar" https://github.com/cjdcordeiro/chisel-releases.git

ADD "https://github.com/canonical/chisel/releases/download/v0.8.1/chisel_v0.8.1_linux_${TARGETARCH}.tar.gz" chisel.tar.gz
RUN tar -xvf chisel.tar.gz -C /usr/bin/
ADD "https://raw.githubusercontent.com/canonical/rocks-toolbox/main/chisel-wrapper" /usr/bin/chisel-wrapper
RUN chmod +x /usr/bin/chisel-wrapper

RUN mkdir /rootfs \
    && chisel-wrapper --generate-dpkg-status /status -- --release ./chisel-releases --root /rootfs \
        base-files_base \
        base-files_release-info \
        ca-certificates_data \
        aspnetcore-runtime-7.0_libs \
    # need to rename binary, otherwise:
    #  "A fatal error was encountered. Cannot execute dotnet when renamed to dotnet7."
    && mv /rootfs/usr/lib/dotnet/dotnet7 /rootfs/usr/lib/dotnet/dotnet \
    && ln -s /usr/lib/dotnet/dotnet /rootfs/usr/bin/
RUN install -d -m 0755 -o "$UID" -g "$GID" "/rootfs/home/$USER" \
    && echo -e "root:x:0:\n$GROUP:x:$GID:" >/rootfs/etc/group \
    && echo -e "root:x:0:0:root:/root:/noshell\n$USER:x:$UID:$GID::/home/$USER:/noshell" >/rootfs/etc/passwd

FROM scratch AS sbom-prep
COPY --from=builder /rootfs /
COPY --from=builder /status /var/lib/dpkg/status

FROM scratch
ENV \
    # Configure web servers to bind to port 8080 when present
    ASPNETCORE_URLS=http://+:8080 \
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true \
    # Set the invariant mode since ICU package isn't included (see https://github.com/dotnet/announcements/issues/20)
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
ARG USER UID GROUP GID

COPY --from=builder /rootfs /
# Workaround for https://github.com/moby/moby/issues/38710
COPY --from=builder --chown="$UID:$GID" "/rootfs/home/$USER" "/home/$USER"

ENTRYPOINT ["/usr/bin/dotnet"]
CMD ["--info"]
