ARG UBUNTU_RELEASE=22.04
ARG USER=app UID=101 GROUP=app GID=101

FROM ubuntu.azurecr.io/ubuntu:$UBUNTU_RELEASE@sha256:c05fa788338c682486f7c353fc1741f8b9b1f2287cbcc86319b2c6f228c2d6f3 AS builder
ARG USER UID GROUP GID TARGETARCH UBUNTU_RELEASE
SHELL ["/bin/bash", "-oeux", "pipefail", "-c"]

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates file \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

ADD "https://github.com/canonical/chisel/releases/download/v0.8.0/chisel_v0.8.0_linux_${TARGETARCH}.tar.gz" chisel.tar.gz
RUN tar -xvf chisel.tar.gz -C /usr/bin/
ADD "https://raw.githubusercontent.com/canonical/rocks-toolbox/main/chisel-wrapper" /usr/bin/chisel-wrapper
RUN chmod +x /usr/bin/chisel-wrapper

RUN mkdir -p /rootfs/etc \
    && install -d -m 0755 -o "$UID" -g "$GID" "/rootfs/home/$USER" \
    && echo -e "root:x:0:\n$GROUP:x:$GID:" >/rootfs/etc/group \
    && echo -e "root:x:0:0:root:/root:/noshell\n$USER:x:$UID:$GID::/home/$USER:/noshell" >/rootfs/etc/passwd

RUN chisel-wrapper --generate-dpkg-status /status -- --release "ubuntu-$UBUNTU_RELEASE" --root /rootfs \
    base-files_base \
    base-files_release-info \
    ca-certificates_data \
    aspnetcore-runtime-6.0_libs \
    && mkdir -p /rootfs/usr/bin \
    && ln -s /usr/lib/dotnet/dotnet /rootfs/usr/bin/

FROM scratch AS sbom-prep
COPY --from=builder /rootfs /
COPY --from=builder /status /var/lib/dpkg/status

FROM scratch
ENV \
    # Configure web servers to bind to port 8080 when present
    ASPNETCORE_URLS=http://+:8080 \
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true
ARG USER UID GROUP GID

COPY --from=builder /rootfs /

# Workaround for https://github.com/moby/moby/issues/38710
COPY --from=builder --chown="$UID:$GID" "/rootfs/home/$USER" "/home/$USER"

ENTRYPOINT ["/usr/bin/dotnet"]
CMD ["--info"]
